CREATE TABLE CKT_ADDON_DEPNT_ADDONS 
(PRODUCT_ID VARCHAR2(40 BYTE),
  SEQUENCE_NUM NUMBER(38,0),
  DEPNT_ADDON_ID VARCHAR2(40 BYTE)
   );
CREATE UNIQUE INDEX CKT_ADDON_DEPNT_ADDONS_P ON CKT_ADDON_DEPNT_ADDONS (PRODUCT_ID,DEPNT_ADDON_ID);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS ADD CONSTRAINT CKT_ADDON_DEPNT_ADDONS_P PRIMARY KEY (PRODUCT_ID,DEPNT_ADDON_ID);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (PRODUCT_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (SEQUENCE_NUM NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (DEPNT_ADDON_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS ADD CONSTRAINT CKT_ADDON_DEPNT_ADDONS_F_1 FOREIGN KEY (PRODUCT_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID) ENABLE;
ALTER TABLE CKT_ADDON_DEPNT_ADDONS ADD CONSTRAINT CKT_ADDON_DEPNT_ADDONS_F_2 FOREIGN KEY (DEPNT_ADDON_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID) ENABLE;
COMMIT;


CREATE TABLE CKT_ADDON_GRP_ADDONS 
(PRODUCT_ID VARCHAR2(40 BYTE),
  SEQUENCE_NUM NUMBER(38,0),
  GRP_ADDON_ID VARCHAR2(40 BYTE)
   );
CREATE UNIQUE INDEX CKT_ADDON_GRP_ADDONS_P ON CKT_ADDON_GRP_ADDONS (PRODUCT_ID,GRP_ADDON_ID);
ALTER TABLE CKT_ADDON_GRP_ADDONS ADD CONSTRAINT CKT_ADDON_GRP_ADDONS_P PRIMARY KEY (PRODUCT_ID,GRP_ADDON_ID);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (PRODUCT_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (SEQUENCE_NUM NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (GRP_ADDON_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_GRP_ADDONS ADD CONSTRAINT CKT_ADDON_GRP_ADDONS_F_1 FOREIGN KEY (PRODUCT_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID) ENABLE;
ALTER TABLE CKT_ADDON_GRP_ADDONS ADD CONSTRAINT CKT_ADDON_GRP_ADDONS_F_2 FOREIGN KEY (GRP_ADDON_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID) ENABLE;
COMMIT;