CREATE TABLE CKT_ADDON_DEPNT_ADDONS
(ASSET_VERSION NUMBER(19,0), 
PRODUCT_ID VARCHAR2(40 BYTE),
  SEQUENCE_NUM NUMBER(38,0),
  DEPNT_ADDON_ID VARCHAR2(40 BYTE)
   );
CREATE UNIQUE INDEX CKT_ADDON_DEPNT_ADDONS_P ON CKT_ADDON_DEPNT_ADDONS (PRODUCT_ID,DEPNT_ADDON_ID,ASSET_VERSION);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS ADD CONSTRAINT CKT_ADDON_DEPNT_ADDONS_P PRIMARY KEY (PRODUCT_ID,DEPNT_ADDON_ID,ASSET_VERSION);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (PRODUCT_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (SEQUENCE_NUM NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (DEPNT_ADDON_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_DEPNT_ADDONS MODIFY (ASSET_VERSION NOT NULL ENABLE);
COMMIT;


CREATE TABLE CKT_ADDON_GRP_ADDONS
(ASSET_VERSION NUMBER(19,0), 
PRODUCT_ID VARCHAR2(40 BYTE),
  SEQUENCE_NUM NUMBER(38,0),
  GRP_ADDON_ID VARCHAR2(40 BYTE)
   );
CREATE UNIQUE INDEX CKT_ADDON_GRP_ADDONS_P ON CKT_ADDON_GRP_ADDONS (PRODUCT_ID,GRP_ADDON_ID,ASSET_VERSION);
ALTER TABLE CKT_ADDON_GRP_ADDONS ADD CONSTRAINT CKT_ADDON_GRP_ADDONS_P PRIMARY KEY (PRODUCT_ID,GRP_ADDON_ID,ASSET_VERSION);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (PRODUCT_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (SEQUENCE_NUM NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (GRP_ADDON_ID NOT NULL ENABLE);
ALTER TABLE CKT_ADDON_GRP_ADDONS MODIFY (ASSET_VERSION NOT NULL ENABLE);
COMMIT;