<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.atg.com/atg.security" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.atg.com/webservices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.atg.com/webservices">
<types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" targetNamespace="http://www.atg.com/webservices"/>
</types>
<import location="atg.security.wsdl" namespace="http://www.atg.com/atg.security"/>
<message name="updatePARCDataFeedServiceInput">
<part name="plansDataXML" type="xsd:string"/>
</message>
<message name="updatePARCDataFeedServiceOutput">
<part name="return" type="xsd:string"/>
</message>
<message name="SecurityException">
<part name="SecurityException" type="ns1:SecurityException"/>
</message>
<portType name="UpdatePARCDataFeedServiceSEI">
<operation name="updatePARCDataFeedService">
<input message="tns:updatePARCDataFeedServiceInput"/>
<output message="tns:updatePARCDataFeedServiceOutput"/>
<fault message="tns:SecurityException" name="SecurityException"/>
</operation>
</portType>
<binding name="UpdatePARCDataFeedServiceSEIBinding" type="tns:UpdatePARCDataFeedServiceSEI">
<operation name="updatePARCDataFeedService">
<input>
<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://www.atg.com/webservices" use="encoded"/>
</input>
<output>
<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://www.atg.com/webservices" use="encoded"/>
</output>
<fault name="SecurityException">
<soap:fault encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://www.atg.com/webservices" use="encoded"/>
</fault>
<soap:operation soapAction=""/>
</operation>
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
</binding>
<service name="UpdatePARCDataFeedServiceSEIService">
<port binding="tns:UpdatePARCDataFeedServiceSEIBinding" name="UpdatePARCDataFeedServiceSEIPort">
<soap:address location="http://10.56.162.92:8180/atgservices/UpdatePARCDataFeedService/updatePARCDataFeedService"/>
</port>
</service>
</definitions>
